AllCops:
  Exclude:
    - 'bin/**/*'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Style/BlockComments:
  Enabled: false
